import Head from "next/head";

const STRATEGY_LABELS = {
  ssg: "Static Site Generator",
  ssr: "Server-side Rendering",
  "client-fetching": "Client-side Data Fetching",
};

export const LargestPrimePage = ({
  maximum,
  largestPrime,
  contentStrategy,
}: {
  maximum: number | string;
  largestPrime: number | null;
  contentStrategy: "ssg" | "ssr" | "client-fetching";
}) => {
  return (
    <>
      <Head>
        <title>
          Datadog Next.js Prime Finder - {STRATEGY_LABELS[contentStrategy]}
        </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>{STRATEGY_LABELS[contentStrategy]}</h1>
        <h3>Largest prime found under {maximum}:</h3>
        <h1 style={{ fontSize: "3em" }}>
          {largestPrime === null ? "Loading..." : largestPrime}
        </h1>
      </main>
    </>
  );
};
