import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [inputValue, setInputValue] = useState(1000000);

  const staticUrl = `/static-html/${inputValue}`;
  const ssrUrl = `/server-side-rendering/${inputValue}`;
  const clientFetchingUrl = `/client-side-fetching/${inputValue}`;

  return (
    <>
      <Head>
        <title>Datadog Next.js Prime Finder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ marginTop: "8px" }}>
          <label style={{ fontSize: "1.5em" }} htmlFor="max">
            Prime search maximum
          </label>
          <input
            style={{ fontSize: "1.5em" }}
            type="text"
            id="max"
            value={inputValue}
            onChange={(e) => {
              setInputValue(Number.parseInt(e.target.value));
            }}
          ></input>
        </div>
        <div
          style={{
            display: "flex",
            flexDirection: "row",
            width: "100%",
            justifyContent: "space-between",
            maxWidth: "1000px",
            marginTop: "4px",
          }}
        >
          <div>
            <h2>Static Generated Page</h2>
            <a href={staticUrl}>{staticUrl}</a>
          </div>
          <div>
            <h2>Server-side Rendering Page</h2>
            <a href={ssrUrl}>{ssrUrl}</a>
          </div>
          <div>
            <h2>Client-side Fetching Page</h2>
            <a href={clientFetchingUrl}>{clientFetchingUrl}</a>
          </div>
        </div>
      </main>
    </>
  );
}
